
  function(deref __deref_ref)
    if(NOT DEFINED "${__deref_ref}")
      return()
    endif()
    set(__deref_ref "${${__deref_ref}}")
    ref_isvalid("${__deref_ref}" trash)
    ans(isref)
    if(NOT isref)
      return()
    endif()
    ref_get(${__deref_ref} trash)
    return_ans()
  endfunction()
