function(ref_print ref)
  if(NOT ref)
    message("undefined ref")
    return()
  endif()
	json_serialize(res "${ref}" INDENTED)

	message("${res}")
	foreach(arg ${ARGN})
		ref_print("${arg}")
	endforeach()
endfunction()