function(ref_print ref)
  if(NOT ref)
    message("undefined ref")
    return()
  endif()
  json_indented(${ref})
  ans(res)
	message("${res}")
	foreach(arg ${ARGN})
		ref_print("${arg}")
	endforeach()
endfunction()