function(ref_istype result ref expectedType)
	ref_isvalid(isref ${ref})
	if(NOT isref)
		return_value(false)
	endif()
	ref_gettype(type ${ref})
	if(NOT "${type}" STREQUAL "${expectedType}" )
		return_value(false)
	endif()
	return_value(true)
endfunction()