function(ref_istype ref expectedType)
	ref_isvalid(${ref})
	ans(isref)

	if(NOT isref)
		return(false)
	endif()
	
	ref_gettype(${ref})
  ans(type)
	if(NOT "${type}" STREQUAL "${expectedType}" )
		return(false)
	endif()
	return(true)
endfunction()