function(ref_new result)
	

	ref_get(__global_ref_count index)
	if(NOT index)
	
		function(ref_new result)
			ref_get(__global_ref_count index)
			math(EXPR index "${index} + 1")
			ref_set(__global_ref_count "${index}")
			if(ARGN)
				set(type "${ARGV1}")
				ref_set("ref:${index}.__type__" "${type}")
			endif()
			return_value("ref:${index}")
		endfunction()
		if(ARGN)
			set(type "${ARGV1}")
			ref_set("ref:1.__type__" "${type}")
		endif()
		ref_set(__global_ref_count 1)
		return_value("ref:1")
	endif()
	message(FATAL_ERROR ref_new)

	math(EXPR index "${index} + 1")
	ref_set(__global_ref_count ${index})
	set(ref "ref:${index}")

	if(ARGN)
		set(type "${ARGV1}")
		#message("setting ref ${result}.__type__ to type ${type}")
		ref_set(${ref}.__type__ "${type}")
#	else()
		#ref_set(${ref}.__type__ "none")
	endif()
	set(${result} ${ref} PARENT_SCOPE)
	return(${result})

endfunction()