  function(cmake_token_range )    
    cmake_tokens("${ARGN}")
    ans(range)
    list_pop_front(range)
    ans(begin)
    list_pop_back(range)
    ans(end)
    return(${begin} ${end})
  endfunction()
