
  function(cmake_invocation_get_arguments_list invocation)
    cmake_invocation_get_arguments_range(${invocation})
    ans_extract(begin end)
    token_find_type(${begin} ${end} "^(nesting)|(nesting_end)|(quoted_argument)|(unquoted_argument)$")
    ans(arguments)
    set(result)
    foreach(argument_token ${arguments})
      map_tryget(${argument_token} literal_value)
      ans(current_value)
      list(APPEND result ${current_value})
    endforeach()  
    return_ref(result)
  endfunction()