
  function(print_tokens start)
    set(end "${ARGN}")
    assign(start = "${start}")
    if(end)
      assign(end = "${end}")
    endif()
    print_vars(start.name)
    print_vars(end)
    cmake_unparse_range("${start}" "${end}")
    ans(res)
    _message("${res}")
  endfunction()
