
  function(token_range start)
    set(end ${ARGN})
    set(current ${start})
    set(tokens)
    while(true)
      if(NOT current OR "${current}" STREQUAL "${end}")
        break()
      endif() 
      list(APPEND tokens ${current})
      map_tryget(${current} next)
      ans(current)
    endwhile()
    return_ref(tokens)
  endfunction()