
  ## using the specified package source gets resolves all dependencies and returns them
  ## in dependency order ie package depending on other package comes after other package
  function(package_dependency_order source)
    function(dependency_hash source dep)
      ref_isvalid(${dep})
      ans(isref)
      if(NOT isref)
        assign(dep = source.resolve("${dep}"))
      endif()
      map_tryget(${dep} uri)
      return_ans()
    endfunction()
    function(dependency_expand source dep)
      ref_isvalid(${dep})
      ans(isref)
      if(NOT isref)
        assign(dep = source.resolve("${dep}"))
      endif()
      assign(deps = dep.package_descriptor.dependencies)
      set(preds)
      foreach(dep ${deps})
        assign(predecessors = source.resolve("${dep}"))
        list(APPEND preds ${predecessors})
      endforeach()

      return_ref(preds)
    endfunction()

    curry3((dep) => dependency_hash("${source}" /dep) )
    ans(hash)
    curry3((dep) => dependency_expand("${source}" /dep) )
    ans(dep)

    topsort("${hash}" "${dep}" ${ARGN})
    ans(order)
    list_reverse(order)
    return_ref(order)
  endfunction()