function(obj_setownproperty ref key )
 obj_nullcheck(${ref})
 set(data ${ARGN})
 if(NOT "${ARGV2}" STREQUAL "RAW")
 	file(WRITE "${ref}/${key}" "${ARGN}")
 else() 	
    #remove RAW
    set(lst ${ARGN})
    escape(lst "${lst}")
    escape(lst "${lst}")
    string(SUBSTRING ${lst} "3" "-1" lst )
 	file(WRITE "${ref}/${key}" ${lst})
 endif()
endfunction()