function(obj_get ref result key)
	obj_getref(${ref} prop_ref ${key})
	if(NOT prop_ref)
		return_value(NOTFOUND)
	endif()
	obj_getrefvalue(${prop_ref} value)
	# just to make sure value is not evaluated too much
	set(${result} ${value} PARENT_SCOPE)
	#return_value(${value})
	#obj_getownproperty(${ref} value ${key})
	#if(NOT value)
	#	obj_getprototype(${ref} proto)
	#	if(proto)
	#		obj_get(${proto} value ${key})
	#	endif()
	#endif()
	#return_value(${value})
endfunction()