file(GLOB dependencies "${CMAKE_CURRENT_LIST_DIR}/dependencies/*" )
file(GLOB script_files "${CMAKE_CURRENT_LIST_DIR}/scripts/*")
foreach(inc ${dependencies} ${script_files})
  include("${inc}")
endforeach()
