function(combinations result listA listB)
	set(res)
	foreach(a ${${listA}})
		foreach(b ${${listB}})
			list(APPEND res "${a}${b}")
		endforeach()
	endforeach()
	set(${result} ${res} PARENT_SCOPE)
endfunction()