# spawns an interactive cmake session
# usage: cmake()
function(icmake)
  while(true)
    echo_append("cmake> ")
    set(cmd)
    set(line "\\")
    set(first true)
    while("${line}" MATCHES ".*\\\\$")
      if(first)
        set(first false)
        set(line "")
      else()
        echo_append("       ")
      endif()

      read_line()
      ans(line)
      if("${line}" MATCHES ".*\\\\$")
        string_substring("${line}" 0 -2)
        ans(theline)
      else()
        set(theline "${line}")
      endif()
      set(cmd "${cmd}\n${theline}")

    endwhile()

    if("${line}" MATCHES "^(quit|exit)$")
      break()
    endif()

    set_ans("${ANS}")
    eval_ref(cmd)
    ans(ANS)
  endwhile()
  return()
endfunction()