 function(function_import_table map function_name)
    map_keys(${map} keys)
    set("ifs" "if(false)\n")
    foreach(key ${keys})
      map_get(${map} command_name ${key})
      set(ifs "${ifs}elseif(\"${key}\" STREQUAL \"\${switch}\" )\n${command_name}(\"\${ARGN}\")\nreturn_ans()\n")
    endforeach()
    set(ifs "${ifs}endif()\n")
  set("evl" "function(${function_name} switch)\n${ifs}\nreturn()\nendfunction()")
     # message(${evl})
      eval("${evl}")
  endfunction()
