function(test)

  return()
  oocmake_config(base_dir)
  ans(dir)
message("tick")
  json3file("${dir}/resources/json.json")
  ans(res)
message("tock")
json_print(${res})
  message("res ${res} ${dir}")
return()
# too slow -->  commented out
  language("${package_dir}/resources/json-language.json")
  ans(json_language)
  file(READ "${package_dir}/resources/expr.json" res)
  eval_json("${res}")
ans(res)
message("res ${res}")
ref_print(${res})
endfunction()