function(call_object)
	function(myfunc result)
		set(was_called true PARENT_SCOPE)
		set(call_context ${this} PARENT_SCOPE)
		return_value("return_value")
	endfunction()
	obj_newfunctor(res myfunc)
	assert(res)
	obj_call(${res} myfunc_result)
	assert(was_called)	
	assert(myfunc_result)
	assert(${myfunc_result} STREQUAL "return_value")
endfunction()