function(nested_bind_call_sameobject)
		function(testfunc1)
			set(inner ${this} PARENT_SCOPE)
		endfunction()

		function(testfunc2)
			 testfunc1()
			set(inner ${inner} PARENT_SCOPE)
			set(outer ${this} PARENT_SCOPE)
		endfunction()

		obj_create(obj)
		obj_pushcontext(${obj})
		testfunc2()
		obj_popcontext()
		assert(${inner} STREQUAL "${obj}")
		assert(${outer} STREQUAL "${obj}")
		#assert(NOT this)
	endfunction()