#this test clears the current scope. calls a test function and elevates all newly
# defined variables to the parent scope
function(scoping)
	function(test)
		scope_push()
		set(a "helo")
		set(b "helo")
		scope_elevate()
		scope_pop()
	endfunction()
	scope_clear()
	assert(NOT a)
	assert(NOT b)
	test()
	assert(a)
	assert(b)
endfunction()