
	function(should_call)
		obj_create(obj)
		function(testfunc)
			set(was_called true PARENT_SCOPE)
		endfunction()
		obj_setfunction(${obj} "func" "testfunc")
		assert(NOT was_called)
		obj_call(${obj} "func")
		assert(was_called)
	endfunction()