function(test)

  stack_new()
  ans(stack)
  stack_isempty(${stack})
  ans(res)
  assert( res)

  stack_push(${stack} "")
  stack_isempty(${stack})
  ans(res)
  assert(NOT res)
  stack_push(${stack} "a")
  stack_push(${stack} "")
  stack_push(${stack} "b")
  stack_pop(${stack})
  ans(res)
  assert("${res}" STREQUAL "b")
  stack_pop(${stack})
  ans(res)
  assert("${res}_" STREQUAL "_")
  stack_pop(${stack})
  ans(res)
  assert("${res}" STREQUAL "a")
  stack_pop(${stack})
  ans(res)
  assert("${res}_" STREQUAL "_")
  stack_pop(${stack})
  ans(res)
  assert("${res}_" STREQUAL "_")
  stack_isempty(res)
  ans(res)
  assert(res)


endfunction()