# parses a hg ref (e.g. result of hg tags ) returning a map
# { name: <identifier>, number:<int>, id:<hash>}
function(hg_parse_ref)
 string(REGEX REPLACE "^_([a-zA-Z0-9_\\.\\/\\-]+)[ ]+([0-9]+):([0-9a-fA-F]+)(.*)$" "\\1;\\2;\\3;\\4" parts "_${ref}")
  map_new()
  ans(ref_struct)
  list_extract(name rev_number rev rest)
  if("${rest}" MATCHES "\\(inactive\\)")
    map_set(${ref_struct} inactive true)
  else()
    map_set(${ref_struct} inactive false)
  endif()


  map_set(${ref_struct} name "${name}")
  map_set(${ref_struct} number "${rev_number}")
  map_set(${ref_struct} id "${rev}")
  return_ref(ref_struct)
endfunction()

function(hg_get_refs)
  hg(branches)
  ans(branches)
  string_split("${branches}" "\n")
  hg(branches)
  ans(tags)  
  string_split("${tags}" "\n")
  ans(tags)


  set(refs)
  foreach(ref ${tags}  )
    hg_parse_ref("${ref}")
    ans(ref)
    map_set("${ref}" type "tag")
    list(APPEND refs "${ref}") 
  endforeach()
  foreach(ref ${branches}  )
    hg_parse_ref("${ref}" )
    ans(ref)
    map_set("${ref}" type "branch")
    list(APPEND refs "${ref}") 
  endforeach()
  return_ref(refs)
endfunction()

function(hg_match_ref ref name number hash type)
  set(name_match true)
  set(number_match true)
  set(type_match true)
  set(hash_match true)
  if(NOT "${name}"  STREQUAL "*")
    map_tryget("${ref}" name)
    ans(ref_name)
    set(name_match false)
    if("${ref_name}" MATCHES "${name}")
      set(name_match true)
    endif()
  endif()

  if(NOT "${number}"  STREQUAL "*")
      map_tryget("${ref}" number)
      ans(ref_number)
      set(number_match false)
      if("${ref_number}" EQUAL "${number}")
        set(number_match true)
      endif()
  endif()

  if(NOT "${hash}" STREQUAL "*")
    map_tryget("${ref}" id)
    ans(ref_hash)
    set(hash_match false)
    if("${ref_hash}" MATCHES "${hash}")
      set(hash_match true)
    endif() 
  endif()

  if(NOT "${type}" STREQUAL "*")
    map_tryget("${ref}" type)
    ans(ref_type)
    set(type_match false)
    if("${ref_type}" STREQUAL "${type}")
      set(type_match true)
    endif()
  endif()

  if(name_match OR number_match OR type_match OR hash_match)
    return(true)
  endif()
  return(false)


endfunction()

function(hg_find_ref refs name number hash type)
  foreach(ref ${refs})
    hg_match_ref("${ref}" "${name}" "${number}" "${hash}" "${type}" )
  endforeach()

endfunction()