# changes the current directory 
function(cd)
  set(args ${ARGN})
  list_extract_flag(args --create)
  ans(create)
  path("${args}")
  ans(path)
 # message("cd ${path}")
  if(NOT IS_DIRECTORY "${path}")
    if(NOT create)
      message(FATAL_ERROR "directory '${path}' does not exist")
      return()
    endif()
    mkdir("${path}")
  endif()
  ref_set(__global_cd_current_directory "${path}")
  return_ref(path)
endfunction()