function(file_find file include_dirs extensions)
    #message("trying to find ${file} in ${include_dirs}")
    set(extensions "false;${extensions}")
    set(include_dirs "false;${include_dirs}")
    foreach(dir ${include_dirs})
      if(dir AND NOT "${dir}"  MATCHES ".*/$")
        set(dir "${dir}/")
      elseif(NOT dir)
        set(dir "")
      endif()

      foreach(extension ${extensions})
        if(extension AND NOT "${extension}" MATCHES "^\\..*" )
          set(extension ".${extension}")
        elseif(NOT extension)
          set(extension "")
        endif()
        set(test_path "${dir}${file}${extension}")
        #message("test_path ${test_path}")
        string(STRIP "${test_path}" test_path)
        if(EXISTS "${test_path}" )
          get_filename_component(file "${test_path}" REALPATH)
          #message("returning ${file}")
          return_ref(file)
        endif()
      endforeach()
    endforeach()
    return()
  endfunction()