## returns the current users home directory on all OSs
## 
function(home_dir)
  shell_get()
  ans(shell)
  if("${shell}" STREQUAL "cmd")
    shell_env_get("HOMEDRIVE")
    ans(dr)
    shell_env_get("HOMEPATH")
    ans(p)
    set(res "${dr}${p}")
    file(TO_CMAKE_PATH "${res}" res)
    #path("${res}")
    #ans(res)
  elseif("${shell}" STREQUAL "bash")
    shell_env_get(HOME)
    ans(res)
  else()
    message(FATAL_ERROR "supported shells: cmd & bash")
  endif() 
  map_set(global home_dir "${res}")
  function(home_dir)
    map_tryget(global home_dir)
    return_ans()
  endfunction()
  return_ref(res)
endfunction()
