
  function(stream_take_string stream str)
    string(LENGTH "${str}" len)
    ref_get(${stream} data)
    string_encode_list("${str}")
    ans(str)
    string_starts_with("${data}" "${str}")
    ans(starts_with)
    if(NOT starts_with)
      return()
    endif()
    string_remove_beginning("${data}" "${str}")
    ans(data)
    ref_set(${stream} "${data}")
    string_decode_list("${str}")
    return_ans()
  endfunction()