function(stream_new data)
    map_create(stream)
    map_set(${stream} index 0)
    string_encode_list("${data}")
    ans(data)
    map_set(${stream} data "${data}")
    stack_new(stack)
    map_set(${stream} stack "${stack}")
    return_ref(stream)
  endfunction()