
function(package_dependency_constraint_clause constraint reason)
  format("${reason}")
  ans(reason)
  set(literals ${ARGN})
  map_new()
  ans(clause)

  map_set(${clause} reason "${reason}")
  foreach(literal ${literals})
    if("${literal}" MATCHES "^!(.+)")
      map_tryget(${CMAKE_MATCH_1} uri)
      ans(uri)
      map_append(${clause} literals "!${uri}")
    else()
      map_tryget(${literal} uri)
      ans(uri)
      map_append(${clause} literals "${uri}")
    endif()
  endforeach()

  map_set(${clause} constraint ${constraint})
  map_append(${constraint} clauses ${clause})

  return(${clause})
endfunction()