function(list_extract lst)
  set(thelist ${${lst}})
  set(args ${ARGN})
  while(true)
    list_pop_front( thelist)
    ans(current_value)
    list_pop_front( args)
    ans(current_arg)
    if(NOT current_arg)
      return()
    endif()
    set(${current_arg} ${current_value} PARENT_SCOPE)
  endwhile()

endfunction()