
function(list_pop_front result lst)
  set(res)
  list_peek_front(res "${lst}")
  if(NOT DEFINED res)
    return_value()
  endif()

  list(LENGTH "${lst}" len)
  if(${len} EQUAL 1) 
    set(${lst} )
  else()
    list(REMOVE_AT "${lst}" 0)
  endif()
  #message("${lst} is ${${lst}}")
  set(${result} ${res} PARENT_SCOPE)
  set(${lst} ${${lst}} PARENT_SCOPE)
endfunction()