
function(list_where __list_where_lst predicate)
	lambda(predicate "${predicate}")
	function_import("${predicate}" as predicate_function)
	foreach(item ${${__list_where_lst}})
		predicate_function(res2 "${item}")
		if(res2)
			list(APPEND result_list ${item})
		endif()
	endforeach()
	return_ref(result_list)
endfunction()