# returns true if value ${a} comes before value ${b} in list _lst
# sets ${result} to true or false
function(list_isinorder  _lst a b)
	list(FIND _lst ${a} indexA)
	list(FIND _lst ${b} indexB)
	if(${indexA} LESS 0)
		return(false)
	endif()
	if(${indexB} LESS 0)
		return(false)
	endif()
	if(${indexA} LESS ${indexB})
		return(true)
	endif()
	return(false)
endfunction()