function(obj_has this result key)
	obj_hasownproperty(${this} res ${key})
	if(NOT res)
		obj_getprototype(${this} proto)
		if(proto)
			obj_has(${proto} res ${key})
		endif()
	endif()
	return_value(${res})
endfunction()