function(obj_get this result key)
	obj_hasownproperty(${this} has_key ${key})
	if(has_key)
		obj_getownproperty(${this} value "${key}")
		set(${result} "${value}" PARENT_SCOPE)
		return()
	endif()
	obj_getprototype(${this} proto)
	if(NOT proto)
		set(${result} PARENT_SCOPE)
		return()
	endif()
	obj_get(${proto} res "${key}")
	set(${result} "${res}" PARENT_SCOPE)
	return()
	obj_getref(${this} prop_ref ${key})
	if(NOT prop_ref)
		return_value(NOTFOUND)
	endif()
	obj_getrefvalue(${prop_ref} value)
	message("obj_get: value ${value}")
	# just to make sure value is not evaluated too much
	set(${result} "${value}" PARENT_SCOPE)
	
endfunction()