function(obj_construct this)
	obj_nullcheck(${this})
	return_if_run_before(${this})
	obj_has(${this} can_init __init__)
	if(NOT can_init)
		return()
	endif()
	obj_callmember(${this} __init__ ${ARGN})
endfunction()