function(replace_first result string_search string_replace string_input)
	string(FIND "${string_input}" "${string_search}" index)
	if("${index}" LESS "0")
		set(${result} "${string_input}" PARENT_SCOPE)
		return()
	endif()
	string(LENGTH "${string_search}" search_length)
	string(SUBSTRING "${string_input}" "0" "${index}" part1)
	math(EXPR index "${index} + ${search_length}")
	string(SUBSTRING "${string_input}" "${index}" "-1" part2)
	set(${result} "${part1}${string_replace}${part2}" PARENT_SCOPE)
endfunction()