function(test)

  set(lst 1 2 3 4 )
  list_pop_front( lst)
  ans(res)
  assert(EQUALS 2 3 4 ${lst})
  assert("${res}" STREQUAL "1")

  set(lst ";0;NOTFOUND; ;asd;bsd; ; ;")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}_" STREQUAL "_")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}" STREQUAL "0")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}" STREQUAL "NOTFOUND")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}" STREQUAL " ")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}" STREQUAL "asd")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}" STREQUAL "bsd")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}" STREQUAL " ")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}" STREQUAL " ")
  list_pop_front( lst)
  ans(arg)
  assert("${arg}_" STREQUAL "_")


endfunction()