# reads a line from the console.  
function(read_line input_message)
    file_tmp("txt" "")
    ans(value_file)
  if(WIN32)
    set(batch_file read.bat)
    set(no_value_hash slkfmslkfl342lk34234osdpi0i34)
    file_tmp("bat" "@echo off\nset val=${no_value_hash}\nset /p val=${input_message}\necho | set /p dummyName=%val%> ${value_file}")
    ans(batch_file)
    execute_process(COMMAND  "${batch_file}")
    file(REMOVE "${batch_file}")
    file(READ "${value_file}" res)
    file(REMOVE "${value_file}")
    string(STRIP "${res}" res)
    if("${res}" STREQUAL "${no_value_hash}")
      return()
    endif()
    return_ref(res)
  else()
    echo_append("${input_message}")
    file_tmp("sh" "#!/bin/bash\nread text\necho -n $text>${value_file}")
    ans(shell_script)
    file(READ "${shell_script}" resu)
    execute_process(COMMAND "chmod" "+x" "${shell_script}" OUTPUT_VARIABLE res)
    execute_process(COMMAND  "${shell_script}"OUTPUT_VARIABLE res)
    file(READ "${value_file}" res)
    file(REMOVE "${shell_script}")
    file(REMOVE "${value_file}")
    return_ref(res)
    endif()
endfunction()
