# reads a line from the console.  
function(read_line input_message)
  if(WIN32)
    set(batch_file read.bat)
    file_tmp("txt" "")
    ans(value_file)
    set(no_value_hash slkfmslkfl342lk34234osdpi0i34)
    file_tmp("bat" "@echo off\nset val=${no_value_hash}\nset /p val=${input_message}\necho | set /p dummyName=%val%> ${value_file}")
    ans(batch_file)
    execute_process(COMMAND  "${batch_file}")
    file(REMOVE "${batch_file}")
    file(READ "${value_file}" res)
    file(REMOVE "${value_file}")
    string(STRIP "${res}" res)
    if("${res}" STREQUAL "${no_value_hash}")
      return()
    endif()
    return_ref(res)
  else()
    file_tmp("sh" "#!/bin/bash\necho -n \"Enter some text > \"read text\necho \"You entered: $text\"")
    message(FATAL_ERROR "only implemented for windows") 
  endif()
endfunction()
