
  function(evaluate str expr)
    set(scope ${ARGN})
    map_isvalid("${scope}" ismap)
    if(NOT ismap)
      map_create(scope)
      foreach(arg ${ARGN})
        map_set(${scope} "${arg}" ${${arg}})
      endforeach()
    endif()
    message("expr ${expr}")
    ast("${str}" "${expr}")
    ans(ast)
    #ref_print(${ast})
    ast_eval(${ast} ${scope})
    if(NOT ismap)
      map_promote(${scope})
    endif()
    return_ans()
  endfunction()