
  function(evaluate str  language expr)
    set(scope ${ARGN})
    map_isvalid("${scope}" ismap)
    if(NOT ismap)
      map_create(scope)
      foreach(arg ${ARGN})
        map_set(${scope} "${arg}" ${${arg}})
      endforeach()
    endif()
  #  message("expr ${expr}")
    ast("${str}" ${language} "${expr}")
    return("gna")
    ans(ast) 
   # ref_print(${ast})
    ast_eval(${ast} ${scope} ${language})
    if(NOT ismap)
      map_promote(${scope})
    endif()
    return_ans()
  endfunction()