
function(expr str)
  expr_compile("${str}")
  ans(symbol)
  #message("${symbol}")
  map_isvalid("${global}" ismap)
  if(NOT ismap)
    map_create(global)
  endif()
  eval("${symbol}")
  ans(res)
  if(NOT ismap)
    map_promote(${global})
  endif()
  return_ref(res)
endfunction()