
  function(token_stream_take stream token_def_or_name)
   # message(FORMAT "trying to take {token_def_or_name.name}")
    map_get(${stream} current current)
    if(NOT current)
      return()
    endif()
    #message(FORMAT "current token is {current.data} it is a {current.definition.name}")
    map_get(${current} definition definition)
    map_get(${definition} name name)
    if("${definition}" STREQUAL "${token_def_or_name}")
      token_stream_move_next(${stream})
      return(${current})
    endif()

    if("${token_def_or_name}" STREQUAL "${name}")
      token_stream_move_next(${stream})
      return(${current})
    endif()
    return()
  endfunction()