  function(format)
    string(ASCII 29 delimiter)
    set(template "${ARGN}")
    string(REGEX MATCHALL "{[^}]*}" matches "${template}")
  #  string(REGEX REPLACE "{([^}]*)}" "${delimiter}//1${delimiter}" template "${template}")
    list_remove_duplicates(matches)
    foreach(match ${matches})
      string(REGEX REPLACE "^{(.*)}$" "\\1" match "${match}")
      assign(value = ${match})
      string(REPLACE "{${match}}" "${value}" template "${template}")
    endforeach()
    return_ref(template)
  endfunction()
