# adds a value to ${current_element}
function(value)
	set(options)
  	set(oneValueArgs KEY)
  	set(multiValueArgs VALUE)
  	set(prefix)
  	cmake_parse_arguments("${prefix}" "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  	if(NOT _VALUE)
		set(_VALUE ${_UNPARSED_ARGUMENTS})
  	endif()
  	if(_KEY)
  		map_set(${current_element} "${_KEY}" "${_VALUE}")
  	else()
		ref_append(${current_element} "${_VALUE}")
	endif()
endfunction()