function(ref_new ref)

	#if(NOT __scope)
	#	set(__scope GLOBAL)
	#endif()
	#if(${__scope} STREQUAL "GLOBAL")
		while(true)
			make_guid(id)
			get_property(prop GLOBAL PROPERTY "ref:global:${id}")
			if(NOT prop)
				set(${ref} "ref:global:type:${id}" PARENT_SCOPE)
				return()
			endif()
		endwhile()
	#elseif(${__scope} STREQUAL "LOCAL")
	#	while(true)
	#		make_guid(id)
	#		if(NOT DEFINED "ref:local:type:${id}")
	#			set(${ref} "ref:local:type:${id}" PARENT_SCOPE)
#				return()
#			endif()
#		endwhile()
#	endif()
endfunction()