macro(peek_back var result)
   get_property(lst GLOBAL PROPERTY ${var})
   list(LENGTH lst len)
   if(${len} LESS 1)
   	set(result NOTFOUND)
   else()
   math(EXPR lst "${len} - 1")
   list(GET lst ${len} ${result})
   #debug_message("peeking front ${result}")
   endif()
endmacro()