function(obj_setownproperty this key )
 obj_nullcheck(${this})
 set(data ${ARGN})
 if(NOT "${ARGV2}" STREQUAL "RAW")
 	file(WRITE "${this}/${key}" "${ARGN}")
 else() 	
    #remove RAW
    set(lst ${ARGN})
    escape(lst "${lst}")
    escape(lst "${lst}")
    string(SUBSTRING ${lst} "3" "-1" lst )
 	file(WRITE "${this}/${key}" ${lst})
 endif()
endfunction()