#returns the prop_ref for obj[key] or notfound (if object itself has the property)
function(obj_getownref this result key)
	obj_hasownproperty(${this} _hasprop ${key})
	if(_hasprop)
		return_value("${this}/${key}")
	endif()
	return_value(NOTFOUND)
endfunction()