
  function(cmakelists_target cmakelists target)
    ref_isvalid("${target}")
    ans(is_ref)
    if(is_ref)
      return(${target})
    endif()
    set(target_name ${target})
    cmakelists_targets("${cmakelists}" "${target_name}")
    ans(targets)
    map_values(${targets})
    ans(target)
    list(LENGTH target count)
    if(NOT "${count}" EQUAL 1)
      error("could not find single target (found {count})")
      return()
    endif()
    return_ref(target)
  endfunction()
