## `(<cmakelists> <file>... [--create-files] )->`
## qualifies the paths relative to the cmaklists file path
function(cmakelists_paths cmakelists)
  set(args ${ARGN})
  list_extract_flag(args --create-files)
  ans(create_files)
  list_extract_flag(arsg --create-dirs)
  ans(create_dir)

  map_tryget(${cmakelists} path)
  ans(path)
  path_parent_dir("${path}")
  ans(dir)
  set(files)
  foreach(file ${args})
    path_qualify(file)
    if(create_dirs AND NOT EXISTS "${file}")
      mkdir("${file}")
    elseif(create_files AND NOT EXISTS "${file}")
      fwrite("${file}" "")
    endif()
    path_relative("${dir}" "${file}")
    ans_append(files)
  endforeach()
  return_ref(files)
endfunction()
