
    function(hg_cached_clone target_dir uri ref)
      set(args ${ARGN})
      list_extract_flag(args --async)
      ans(async)
      pushd("${target_dir}" --create)
      ans(target_dir)
      path_qualify(target_dir)


      if(async)
        ## this actually works...
        set(script "
          include(${oocmake_base_dir}/cmakepp.cmake)
          hg(clone ${remote_uri} ${target_dir})
          hg(update)
          set(ref ${ref})
          if(ref)
            hg(checkout ${ref})
          endif()
        ")
        process_start_script("${script}")
        ans(process_handle)

        echo_append("cloning hg repository '${uri}' ...")
        while(true)
          process_isrunning(${process_handle})
          ans(running)
          if(NOT running)
            break()
          endif()
          echo_append(".")
        endwhile()
        message("... done")

        process_wait(${process_handle})
        ans(res)
        return_ref(target_dir)
      else()

        hg(clone "${remote_uri}" "${target_dir}")
        hg(update)
        if(ref)
          hg(checkout "${ref}")
        endif()
        popd()
        return_ref(target_dir)
      endif()
    endfunction()