function(json3file file)
  file_make_temporary("")
  ans(tmp)
  rm("${tmp}")
  cmakeJsonParser("${file}" "${tmp}" --result)
  include("${tmp}")
  ans(res2)
  rm("${tmp}")
  return_ref(res2)
endfunction()