
  function(json2 input) 
    set(cached ${ARGN})
    if(cached)
      string(MD5 cache_key "${input}" )
      if(EXISTS "${cutil_temp_dir}/json2/${cache_key}.json")
        message("getting cached")
        include("${cutil_temp_dir}/json2/${cache_key}.json")
        return_ans()

      endif()
    endif()
    language("json2")
    ans(lang)
    if(NOT lang)
      language("${cutil_package_dir}/oo-cmake/resources/json.json")
    endif()
    lang2(output json2 input "${input}" def "json")
    ans(res)
    if(cached)
      qm_serialize("${res}")
      ans(qm)
      file(WRITE "${cutil_temp_dir}/json2/${cache_key}.json" "${qm}")
    endif()
    return_ref(res)
  endfunction()