function(map_issubsetof result superset subset)
	map_keys(${subset} keys)
	foreach(key ${keys})
		map_tryget(${superset} superValue ${key})
		map_tryget(${subset} subValue ${key})

		map_isvalid(${superValue} issupermap)
		map_isvalid(${subValue} issubmap)
		if(issubmap AND issubmap)
			map_issubsetof(res ${superValue} ${subValue})
			if(NOT res)
				return_value(false)
			endif()
		else()
			list_isvalid(${superValue} islistsuper)
			list_isvalid(${subValue} islistsub)
			if(islistsub AND islistsuper)
				ref_get(${superValue} superValue)
				ref_get(${subValue} subValue)
			endif()
			list_equal(res "${superValue}" "${subValue}")
			if(NOT res)
				return_value(false)
			endif()
		endif()
	endforeach()
	return_value(true)
endfunction()