
function(map_has this result key )
	#map_check(${this})
	map_keys(${this} keys)
	list(FIND keys "${key}" res)
	if(${res} LESS 0)
		return_value(false)
	else()
		return_value(true)
	endif()
endfunction()
