
function(map_format input)
	string(REGEX MATCHALL "{([^}{]*)}" matches "${input}")
	foreach(match ${matches})
		string(LENGTH ${match} len)
		math(EXPR len "${len} - 2")
		string(SUBSTRING ${match} 1 ${len} nav)
		map_navigate(res "${nav}")
		# escape regex chars ([] .*)
		string(REGEX REPLACE "(\\]|\\.|\\[|\\*)" "\\\\\\1" match "${match}")
		string(REGEX REPLACE "${match}" "${res}" input "${input}")
	endforeach()
	return_ref(input)
endfunction()