
function(map_clone_deep original)
  map_clone_shallow("${original}")
  ans(result)
    
  map_isvalid("${result}" ismap)
  if(ismap) 
    map_keys("${result}" keys)
    foreach(key ${keys})
      map_get(${result} value ${key})
      map_clone_deep("${value}")
      ans(cloned_value)
      map_set(${result} ${key} ${cloned_value})
    endforeach()
  endif()
  return(${result})
endfunction()