# prints all values of the map
function(map_print this)
	map_keys(${this} )
  ans(keys)
	foreach(key ${keys})
		map_get(${this}   ${key})
    ans(value)
		message("${key}: ${value}")
	endforeach()
endfunction()