
function(map_makelist map key)
	map_tryget(${map}  "${key}")
	ans(lst)
	if(NOT lst)
		return()
	endif()
	list_isvalid(${lst} islist)
	if(islist)
		return()
	endif()
	list_new(res)
	ref_set(${res} ${lst})
	map_set(${map} ${key} ${res})
endfunction()