 function(map_template_evaluate_scoped map scope)
 #todo -> needs to be implemented to correctly do recursion
 ## needs to have max iterations
    map_keys(${map})
    ans(keys)

    map_clone_deep(${map})
    ans(clone)
    if("${map}" STREQUAL "${scope}")
        set(scope "${clone}")
    endif()
        
    set(changed true)
    while(changed)
        set(changed false)
        foreach(key ${keys})
            map_tryget(${map} "${key}")
            ans(template)
            map_tryget(${clone} "${key}")
            ans(previousValue)
            template_run_scoped(${scope} "${template}" )
            ans(value)
            if(NOT "${value}_" STREQUAL "${previousValue}_")
                map_set(${clone} "${key}" "${value}")
                set(changed true)
            endif()
        endforeach()
    endwhile()

    if(changed)
        return()
    else()
        return(${clone})
    endif()
 endfunction()