function(obj_setownproperty this key )
 	map_set(${this} "${key}" "${ARGN}")
 	#obj_nullcheck(${this})
 	#set(data ${ARGN})
 	#if("${key}" STREQUAL "__call__")
 	#	obj_has(${this} res print)
 	#endif()
 	#file(WRITE "${this}/${key}" "${ARGN}")
 
 endfunction()