function(map_equal result mapA mapB)

	map_keys(${mapA} )
	ans(keysA)
	map_keys(${mapB} )
	ans(keysB)

	list(SORT keysA)
	list(SORT keysB)

	list_equal(keys_equal keysA keysB)
	if(NOT keys_equal)
		return_value(false)
	endif()

	foreach(key ${keysA})
		map_get(${mapA}  ${key})
		ans(valA)
		map_get(${mapB}  ${key})
		ans(valB)
		list_equal(val_equal ${valA} ${valB})
		if(NOT val_equal)
			return_value(false)
		endif()
	endforeach()
	return_value(true)
endfunction()