function(file_tempdir result)
	#string(MAKE_C_IDENTIFIER id "${ARGN}")
	string_normalize_string(id "${ARGN}")
	set(tempdir "${cutil_temp_dir}/file_tempdir/${id}")
	set(i 0)
	while(true)
		if(NOT EXISTS "${tempdir}_${i}")
			set(${result} "${tempdir}_${i}" PARENT_SCOPE)
			file(MAKE_DIRECTORY "${tempdir}_${i}")
			return()
		endif()
		math(EXPR i "${i} + 1")
	endwhile()
endfunction()