function(map_get  id result key)
 map_getkeys( ${id} keys)
 list(FIND keys ${key} found)
 if(${found} EQUAL "-1")
 	return_value(NOTFOUND)
 else()
  	obj_get( ${id} val ${key})
  	return_value(${val})
 endif() 
endfunction()