
function(obj_setfunction this)
	set(args ${ARGN})
	list(LENGTH args argc)
	if(${argc} EQUAL 1)
		list(GET args 0 func)
		get_function_string(func "${func}")
		parse_function(func "${func}")
		set(key "${func_name}")
	elseif(${argc} EQUAL 2)
		list(GET args 0 key)
		LIST(GET args 1 func)
		get_function_string(func "${func}")
	endif()
	obj_set(${this} ${key} "${func}")	
endfunction()