function(obj_has ref result key)
	obj_hasownproperty(${ref} res ${key})
	if(NOT res)
		obj_getprototype(${ref} proto)
		if(proto)
			obj_has(${proto} res ${key})
		endif()
	endif()
	return_value(${res})
endfunction()