macro(obj_call this)
	is_object(obj_call_is_obj ${this})
	is_member(obj_call_is_mem ${this})
	is_function(obj_call_is_func ${this})		
		
	if(obj_call_is_obj)
		obj_callobject(${this} ${ARGN})
	elseif(obj_call_is_mem AND obj_call_is_func)
		obj_callref(${this} ${ARGN})
		return()
	elseif(obj_call_is_func)
		message(FATAL_ERROR "implement call func")
	else()
		message(FATAL_ERROR "could not call ${this}")
	endif()

endmacro()