
function(semver_constraint_compiled_evaluate compiled_constraint version )
  nav("compiled_constraint.elements")
  ans(elements)
  nav("compiled_constraint.template")
  ans(template)

  #message("elements ${elements}")
  #message("template ${template}")
  foreach(element ${elements})
    semver_constraint_evaluate_element("${element}" "${version}")
    ans(res)
    string(REPLACE "${element}" "${res}" template "${template}")
  endforeach()
  if(${template})
    return(true)
  endif()
  return(false)
endfunction()