function(semver_constraint_compile compiled_constraint result_elements constraint)
  set(ops "\\(\\)\\|,!=~><")
  string(REGEX REPLACE ">=([^${ops}]+)" "(>\\1|=\\1)" constraint "${constraint}")
  string(REGEX REPLACE "<=([^${ops}]+)" "(<\\1|=\\1)" constraint "${constraint}")

  string(REPLACE "!" ";NOT;" constraint "${constraint}")
  string(REPLACE "," ";AND;" constraint "${constraint}")
  string(REPLACE "|" ";OR;" constraint "${constraint}")
  string(REPLACE ")" ";);" constraint "${constraint}")
  string(REPLACE "(" ";(;" constraint "${constraint}")
  set(elements ${constraint})
  list(REMOVE_DUPLICATES elements)
  list(REMOVE_ITEM elements "AND" "OR" "NOT" "(" ")" )
  set(${result_elements} ${elements} PARENT_SCOPE)
  set(${compiled_constraint} "${constraint}" PARENT_SCOPE)
endfunction()