# returns true if ref is a valid reference and its type is 'map'
function(is_map  ref )

	is_address("${ref}")
	ans(isref)
	if(NOT isref)
		return(false)
	endif()
	address_type_get("${ref}")
  ans(type)
	if(NOT "${type}" STREQUAL "map")
		return(false)
	endif()
	return(true)
endfunction()