macro(map_has this result key )  
  get_property(${result} GLOBAL PROPERTY "${this}.${key}" SET)
  #if(res)
  #  return_value(true)
  #endif()
  #return_value(false)
endmacro()
#function(map_has this result key )  
#  get_property(res GLOBAL PROPERTY "${this}.${key}" SET)
#  if(res)
#    return_value(true)
#  endif()
#  return_value(false)
#endfunction()
