function(map_delete this)
	map_exists(${this} )
	ans(res)
	if(NOT res)
		return()
	endif()
	map_check(${this})
	map_keys(${this} )
	ans(keys)

	foreach(key ${keys})
		map_remove(${this} ${key})
	endforeach()
	set_property(GLOBAL PROPERTY ${this})
endfunction()