
  function(cmakepp_compile_file source)
    set(target ${ARGN})

    fread("${source}")
    ans(content)
    cmakepp_compile("${content}")
    ans(content)
    if(NOT target)
      fwrite_temp("${content}" cmakepp)
      ans(target)
    else()
      fwrite("${target}" "${content}")
      ans(target)
    endif()
    return_ref(target)
  endfunction()
