function(interpret_lvalue tokens argument)
  interpret_scope_lvalue("${tokens}" "${argument}")
  ans(ast)
  if(ast)
    return(${ast})
  endif()

  interpret_navigation_lvalue("${tokens}" "${argument}")
  ans(ast)
  if(ast)
    return(${ast})
  endif()

  throw("could not interpret lvalue")
endfunction()