
## platform specific implementation for process_isrunning under windows
function(process_isrunning_Windows handlish)    
  process_handle("${handlish}")    
  ans(handle)    
  map_tryget(${handle} status)
  ans(status)
  if("${status}_" STREQUAL "complete" )
    return(false)
  endif()
  map_tryget(${handle} pid)
  ans(pid)
  win32_tasklist(-FO CSV -FI "PID eq ${pid}" -FI "STATUS eq Running")    
  ans(res)
  if("${res}" MATCHES "PID" AND "${res}" MATCHES "${pid}")
    map_set(${handle} status "running")
    return(true)
  endif()    
  map_set(${handle} status "complete")
  return(false)
endfunction()