function(git_read_single_file repository branch path )
  file_tempdir()
  ans(tmp_dir)
  git(--cwd "${tmp_dir}")
  set(branch_arg)
  if(branch)
    set(branch_arg --branch "${branch}") 
  endif()

  git(clone --no-checkout ${branch_arg} --depth 1 "${repository}" "${tmp_dir}" RESULT success)
  if(NOT success)
    #message(faield1)
    return_value()
  endif()

  if(NOT branch)
    set(branch HEAD)
  endif()

  git(show --format=raw "${branch}:${path}" STDOUT res RESULT success --cwd "${tmp_dir}")
  #message("${res}")
  if(NOT success)
   # message(faield2)
    return_value()
  endif()
  return_ref(res)
  
endfunction()