
  function(package_source_resolve_all package_source)
    set(args ${ARGN})
    list_extract_labelled_value(args --cache)
    ans(cache)
    if(NOT cache)
      map_new()
      ans(cache)
    endif()


    map_new()
    ans(mappings)
    set(uris)
    foreach(admissable_uri ${ARGN})
      call(package_source.query("${admissable_uri}"))
      ans(dependable_uri)
      foreach(current_uri ${dependable_uri})
        map_append(${mappings} "${current_uri}" "${admissable_uri}")
        map_append(${mappings} "${admissable_uri}" "${current_uri}")
      endforeach()
      list(APPEND uris ${dependable_uri})
    endforeach()
  

    set(package_handles)
    foreach(uri ${uris})
      map_tryget(${cache} "${uri}")
      ans(package_handle)
      if(NOT package_handle)
        call(package_source.resolve("${uri}"))
        ans(package_handle)
        map_tryget("${package_handle}" uri)
        ans(uri)
        map_set("${cache}" "${uri}" ${package_handle})
        map_tryget(${mappings} ${uri})
      endif()
      list(APPEND package_handles ${package_handle})
    endforeach()
    return_ref(package_handles)
  endfunction()