function(obj_get this  key)
	obj_hasownproperty("${this}" has_key "${key}")
	if(has_key)
		obj_getownproperty("${this}" value "${key}")
		return_ref(value)
	endif()
	obj_getprototype("${this}" proto)
	if(NOT proto)
		return()
	endif()
	obj_get("${proto}"  "${key}")
	ans(res)
	return_ref(res)
endfunction()


