function(obj_get this result key)
	obj_hasownproperty("${this}" has_key "${key}")
	if(has_key)
		obj_getownproperty("${this}" value "${key}")
		set(${result} "${value}" PARENT_SCOPE)
		return_ref(value)
	endif()
	obj_getprototype("${this}" proto)
	if(NOT proto)
		set(${result} PARENT_SCOPE)
		return()
	endif()
	obj_get("${proto}" res "${key}")
	set(${result} "${res}" PARENT_SCOPE)
	return_ref(res)
endfunction()