function(type_get result type)
	if(NOT COMMAND ${type})
		message(FATAL_ERROR "obj_new: only cmake functions are allowed as types, '${type}' is not function")
	endif()	
	set(base)
	#get_property(base GLOBAL PROPERTY "type_${type}")
	if(NOT base)
		obj_create(base)
		set_property(GLOBAL PROPERTY "type_${type}" "${base}")
		obj_set(${base} __init__ "${type}")
	endif()
	return_value(${base})
endfunction()