
  macro(navigation_expression_unpack ref)
    if("${${ref}}" MATCHES "^\\[.*\\]$")
      string(REGEX REPLACE "\\[(.*)\\]" "\\1" ${ref}.range "${${ref}}")
      set(${ref}.property "")
      set(${ref}.is_range true )
      set(${ref}.is_property false )
    else()      
      set(${ref}.range "0:*")
      set(${ref}.property ${${ref}})
      set(${ref}.is_range false)
      set(${ref}.is_property true )  
    endif()
    range_parse(${ref}.range)
    range_partial_unpack(${ref}.range)
      
  endmacro()