
  macro(navigation_expression_unpack ref)
    if("${${ref}}" MATCHES "^\\[.*\\]$")
      string(REGEX REPLACE "\\[(.*)\\]" "\\1" ${ref}.range "${${ref}}")
      range_unpack(${ref}.range)
      set(${ref}.property "")
      set(${ref}.is_range true )
      set(${ref}.is_property false )
    else()      
      set(${ref}.range "0:*")
      range_unpack(${ref}.range)
      set(${ref}.property ${${ref}})
      set(${ref}.is_range false)
      set(${ref}.is_property true )  
    endif()
  endmacro()