
  function(ref_nav_get current_value)
    set(expression ${ARGN})
    string_take(expression "&")
    ans(return_lvalue)

    navigation_expression_parse("${expression}")
    ans(expression)

    set(current_ref)
    set(current_property)
    set(current_ranges)
    foreach(current_expression ${expression})
      if("${current_expression}" MATCHES "^[<>].*[<>]$")
        list_range_try_get(current_value "${current_expression}")
        ans(current_value)
        list(APPEND current_ranges ${current_expression})
      else()
        map_isvalid("${current_value}")
        ans(is_ref)

        if(NOT is_ref)
          break()
        endif()
        set(current_ref "${current_value}")
        set(current_property "${current_expression}")
        set(current_ranges)

        ref_prop_get("${current_value}" "${current_expression}")
        ans(current_value)
      endif()
    endforeach()
    if(return_lvalue)
      map_capture_new(ref:current_ref property:current_property range:current_ranges value:current_value --reassign)
      return_ans()
    endif()
    return_ref(current_value)

  endfunction()
