  # returns true if given code is a valid lambda expression
  function(lambda_isvalid code)
    string_split_at_first(lambda_signature partB "${code}" "->")
   # message("signature ${lambda_signature}")
    string(STRIP "${lambda_signature}" lambda_signature)
    string_ends_with("${lambda_signature}" ")")
    ans(ok)
    if(NOT ok)
      return(false)
  endif()
    string_starts_with("${lambda_signature}" "(")
    ans(ok)
    if(NOT ok)
      return(false)
    endif()
    return(true)
  endfunction()
