function(proto_declarefunction result)
	obj_get(${this}  __proto__)
  ans(proto)
	if(NOT proto)
		message(FATAL_ERROR "proto_declarefunction: expected prototype to be present")
	endif()
	set(res ${result})
	obj_declarefunction(${proto} ${res})
	set(${result} ${${res}} PARENT_SCOPE)
endfunction()