#inherits from base (if base is an objct it will be set as the prototype of this)
# if base is a function / constructor then a base object will be constructed and set
# as the prototy of this
function(this_inherit baseType)
	type_get(base ${baseType})
	obj_setprototype(${__proto__} ${base})
	obj_get(${base} super __init__)
	set(__proto__ ${base})
	import_function("${super}" as base_constructor REDEFINE)	
	result_clear()
	base_constructor(${ARGN})
	result(instance)
	if(instance)
		set(this "${instance}" PARENT_SCOPE)
	endif()
endfunction()